// Generated by gencpp from file person_service/s_c_person.msg
// DO NOT EDIT!


#ifndef PERSON_SERVICE_MESSAGE_S_C_PERSON_H
#define PERSON_SERVICE_MESSAGE_S_C_PERSON_H

#include <ros/service_traits.h>


#include <person_service/s_c_personRequest.h>
#include <person_service/s_c_personResponse.h>


namespace person_service
{

struct s_c_person
{

typedef s_c_personRequest Request;
typedef s_c_personResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct s_c_person
} // namespace person_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::person_service::s_c_person > {
  static const char* value()
  {
    return "c198113e7dd9cc5c9fd5f271c8479b39";
  }

  static const char* value(const ::person_service::s_c_person&) { return value(); }
};

template<>
struct DataType< ::person_service::s_c_person > {
  static const char* value()
  {
    return "person_service/s_c_person";
  }

  static const char* value(const ::person_service::s_c_person&) { return value(); }
};


// service_traits::MD5Sum< ::person_service::s_c_personRequest> should match 
// service_traits::MD5Sum< ::person_service::s_c_person > 
template<>
struct MD5Sum< ::person_service::s_c_personRequest>
{
  static const char* value()
  {
    return MD5Sum< ::person_service::s_c_person >::value();
  }
  static const char* value(const ::person_service::s_c_personRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::person_service::s_c_personRequest> should match 
// service_traits::DataType< ::person_service::s_c_person > 
template<>
struct DataType< ::person_service::s_c_personRequest>
{
  static const char* value()
  {
    return DataType< ::person_service::s_c_person >::value();
  }
  static const char* value(const ::person_service::s_c_personRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::person_service::s_c_personResponse> should match 
// service_traits::MD5Sum< ::person_service::s_c_person > 
template<>
struct MD5Sum< ::person_service::s_c_personResponse>
{
  static const char* value()
  {
    return MD5Sum< ::person_service::s_c_person >::value();
  }
  static const char* value(const ::person_service::s_c_personResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::person_service::s_c_personResponse> should match 
// service_traits::DataType< ::person_service::s_c_person > 
template<>
struct DataType< ::person_service::s_c_personResponse>
{
  static const char* value()
  {
    return DataType< ::person_service::s_c_person >::value();
  }
  static const char* value(const ::person_service::s_c_personResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PERSON_SERVICE_MESSAGE_S_C_PERSON_H
