// Generated by gencpp from file simple_client_server/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SIMPLE_CLIENT_SERVER_MESSAGE_ADDTWOINTS_H
#define SIMPLE_CLIENT_SERVER_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <simple_client_server/AddTwoIntsRequest.h>
#include <simple_client_server/AddTwoIntsResponse.h>


namespace simple_client_server
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace simple_client_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::simple_client_server::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::simple_client_server::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::simple_client_server::AddTwoInts > {
  static const char* value()
  {
    return "simple_client_server/AddTwoInts";
  }

  static const char* value(const ::simple_client_server::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::simple_client_server::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::simple_client_server::AddTwoInts > 
template<>
struct MD5Sum< ::simple_client_server::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::simple_client_server::AddTwoInts >::value();
  }
  static const char* value(const ::simple_client_server::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::simple_client_server::AddTwoIntsRequest> should match 
// service_traits::DataType< ::simple_client_server::AddTwoInts > 
template<>
struct DataType< ::simple_client_server::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::simple_client_server::AddTwoInts >::value();
  }
  static const char* value(const ::simple_client_server::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::simple_client_server::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::simple_client_server::AddTwoInts > 
template<>
struct MD5Sum< ::simple_client_server::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::simple_client_server::AddTwoInts >::value();
  }
  static const char* value(const ::simple_client_server::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::simple_client_server::AddTwoIntsResponse> should match 
// service_traits::DataType< ::simple_client_server::AddTwoInts > 
template<>
struct DataType< ::simple_client_server::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::simple_client_server::AddTwoInts >::value();
  }
  static const char* value(const ::simple_client_server::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIMPLE_CLIENT_SERVER_MESSAGE_ADDTWOINTS_H
