// Generated by gencpp from file learning_service/AddTwoInts.msg
// DO NOT EDIT!


#ifndef LEARNING_SERVICE_MESSAGE_ADDTWOINTS_H
#define LEARNING_SERVICE_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <learning_service/AddTwoIntsRequest.h>
#include <learning_service/AddTwoIntsResponse.h>


namespace learning_service
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace learning_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::learning_service::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::learning_service::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::learning_service::AddTwoInts > {
  static const char* value()
  {
    return "learning_service/AddTwoInts";
  }

  static const char* value(const ::learning_service::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::learning_service::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::learning_service::AddTwoInts > 
template<>
struct MD5Sum< ::learning_service::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::learning_service::AddTwoInts >::value();
  }
  static const char* value(const ::learning_service::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::learning_service::AddTwoIntsRequest> should match 
// service_traits::DataType< ::learning_service::AddTwoInts > 
template<>
struct DataType< ::learning_service::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::learning_service::AddTwoInts >::value();
  }
  static const char* value(const ::learning_service::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::learning_service::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::learning_service::AddTwoInts > 
template<>
struct MD5Sum< ::learning_service::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::learning_service::AddTwoInts >::value();
  }
  static const char* value(const ::learning_service::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::learning_service::AddTwoIntsResponse> should match 
// service_traits::DataType< ::learning_service::AddTwoInts > 
template<>
struct DataType< ::learning_service::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::learning_service::AddTwoInts >::value();
  }
  static const char* value(const ::learning_service::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEARNING_SERVICE_MESSAGE_ADDTWOINTS_H
