(cl:defpackage action_homework-msg
  (:use )
  (:export
   "<ROBOT_MOVEACTION>"
   "ROBOT_MOVEACTION"
   "<ROBOT_MOVEACTIONFEEDBACK>"
   "ROBOT_MOVEACTIONFEEDBACK"
   "<ROBOT_MOVEACTIONGOAL>"
   "ROBOT_MOVEACTIONGOAL"
   "<ROBOT_MOVEACTIONRESULT>"
   "ROBOT_MOVEACTIONRESULT"
   "<ROBOT_MOVEFEEDBACK>"
   "ROBOT_MOVEFEEDBACK"
   "<ROBOT_MOVEGOAL>"
   "ROBOT_MOVEGOAL"
   "<ROBOT_MOVERESULT>"
   "ROBOT_MOVERESULT"
  ))

