; Auto-generated. Do not edit!


(cl:in-package action_homework-msg)


;//! \htmlinclude robot_moveGoal.msg.html

(cl:defclass <robot_moveGoal> (roslisp-msg-protocol:ros-message)
  ((pose_x
    :reader pose_x
    :initarg :pose_x
    :type cl:float
    :initform 0.0)
   (pose_y
    :reader pose_y
    :initarg :pose_y
    :type cl:float
    :initform 0.0))
)

(cl:defclass robot_moveGoal (<robot_moveGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <robot_moveGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'robot_moveGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action_homework-msg:<robot_moveGoal> is deprecated: use action_homework-msg:robot_moveGoal instead.")))

(cl:ensure-generic-function 'pose_x-val :lambda-list '(m))
(cl:defmethod pose_x-val ((m <robot_moveGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_homework-msg:pose_x-val is deprecated.  Use action_homework-msg:pose_x instead.")
  (pose_x m))

(cl:ensure-generic-function 'pose_y-val :lambda-list '(m))
(cl:defmethod pose_y-val ((m <robot_moveGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_homework-msg:pose_y-val is deprecated.  Use action_homework-msg:pose_y instead.")
  (pose_y m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <robot_moveGoal>) ostream)
  "Serializes a message object of type '<robot_moveGoal>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'pose_x))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'pose_y))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <robot_moveGoal>) istream)
  "Deserializes a message object of type '<robot_moveGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'pose_x) (roslisp-utils:decode-single-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'pose_y) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<robot_moveGoal>)))
  "Returns string type for a message object of type '<robot_moveGoal>"
  "action_homework/robot_moveGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'robot_moveGoal)))
  "Returns string type for a message object of type 'robot_moveGoal"
  "action_homework/robot_moveGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<robot_moveGoal>)))
  "Returns md5sum for a message object of type '<robot_moveGoal>"
  "9fb7694c5d0ece70c45eb28c876fc79c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'robot_moveGoal)))
  "Returns md5sum for a message object of type 'robot_moveGoal"
  "9fb7694c5d0ece70c45eb28c876fc79c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<robot_moveGoal>)))
  "Returns full string definition for message of type '<robot_moveGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#定义目标信息goal~%float32 pose_x~%float32 pose_y~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'robot_moveGoal)))
  "Returns full string definition for message of type 'robot_moveGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#定义目标信息goal~%float32 pose_x~%float32 pose_y~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <robot_moveGoal>))
  (cl:+ 0
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <robot_moveGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'robot_moveGoal
    (cl:cons ':pose_x (pose_x msg))
    (cl:cons ':pose_y (pose_y msg))
))
