; Auto-generated. Do not edit!


(cl:in-package action_homework-msg)


;//! \htmlinclude robot_moveFeedback.msg.html

(cl:defclass <robot_moveFeedback> (roslisp-msg-protocol:ros-message)
  ((percent_complete
    :reader percent_complete
    :initarg :percent_complete
    :type cl:float
    :initform 0.0))
)

(cl:defclass robot_moveFeedback (<robot_moveFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <robot_moveFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'robot_moveFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action_homework-msg:<robot_moveFeedback> is deprecated: use action_homework-msg:robot_moveFeedback instead.")))

(cl:ensure-generic-function 'percent_complete-val :lambda-list '(m))
(cl:defmethod percent_complete-val ((m <robot_moveFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_homework-msg:percent_complete-val is deprecated.  Use action_homework-msg:percent_complete instead.")
  (percent_complete m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <robot_moveFeedback>) ostream)
  "Serializes a message object of type '<robot_moveFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'percent_complete))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <robot_moveFeedback>) istream)
  "Deserializes a message object of type '<robot_moveFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'percent_complete) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<robot_moveFeedback>)))
  "Returns string type for a message object of type '<robot_moveFeedback>"
  "action_homework/robot_moveFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'robot_moveFeedback)))
  "Returns string type for a message object of type 'robot_moveFeedback"
  "action_homework/robot_moveFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<robot_moveFeedback>)))
  "Returns md5sum for a message object of type '<robot_moveFeedback>"
  "d342375c60a5a58d3bc32664070a1368")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'robot_moveFeedback)))
  "Returns md5sum for a message object of type 'robot_moveFeedback"
  "d342375c60a5a58d3bc32664070a1368")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<robot_moveFeedback>)))
  "Returns full string definition for message of type '<robot_moveFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#定义周期反馈消息feedback~%float32 percent_complete~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'robot_moveFeedback)))
  "Returns full string definition for message of type 'robot_moveFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#定义周期反馈消息feedback~%float32 percent_complete~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <robot_moveFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <robot_moveFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'robot_moveFeedback
    (cl:cons ':percent_complete (percent_complete msg))
))
