; Auto-generated. Do not edit!


(cl:in-package action_homework-msg)


;//! \htmlinclude robot_moveResult.msg.html

(cl:defclass <robot_moveResult> (roslisp-msg-protocol:ros-message)
  ((finalpose_x
    :reader finalpose_x
    :initarg :finalpose_x
    :type cl:float
    :initform 0.0)
   (finalpose_y
    :reader finalpose_y
    :initarg :finalpose_y
    :type cl:float
    :initform 0.0))
)

(cl:defclass robot_moveResult (<robot_moveResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <robot_moveResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'robot_moveResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action_homework-msg:<robot_moveResult> is deprecated: use action_homework-msg:robot_moveResult instead.")))

(cl:ensure-generic-function 'finalpose_x-val :lambda-list '(m))
(cl:defmethod finalpose_x-val ((m <robot_moveResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_homework-msg:finalpose_x-val is deprecated.  Use action_homework-msg:finalpose_x instead.")
  (finalpose_x m))

(cl:ensure-generic-function 'finalpose_y-val :lambda-list '(m))
(cl:defmethod finalpose_y-val ((m <robot_moveResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_homework-msg:finalpose_y-val is deprecated.  Use action_homework-msg:finalpose_y instead.")
  (finalpose_y m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <robot_moveResult>) ostream)
  "Serializes a message object of type '<robot_moveResult>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'finalpose_x))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'finalpose_y))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <robot_moveResult>) istream)
  "Deserializes a message object of type '<robot_moveResult>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'finalpose_x) (roslisp-utils:decode-single-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'finalpose_y) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<robot_moveResult>)))
  "Returns string type for a message object of type '<robot_moveResult>"
  "action_homework/robot_moveResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'robot_moveResult)))
  "Returns string type for a message object of type 'robot_moveResult"
  "action_homework/robot_moveResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<robot_moveResult>)))
  "Returns md5sum for a message object of type '<robot_moveResult>"
  "70fbee4bb3e7c94c5c08525cb743c16d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'robot_moveResult)))
  "Returns md5sum for a message object of type 'robot_moveResult"
  "70fbee4bb3e7c94c5c08525cb743c16d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<robot_moveResult>)))
  "Returns full string definition for message of type '<robot_moveResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#定义结果信息result~%float32 finalpose_x~%float32 finalpose_y~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'robot_moveResult)))
  "Returns full string definition for message of type 'robot_moveResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#定义结果信息result~%float32 finalpose_x~%float32 finalpose_y~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <robot_moveResult>))
  (cl:+ 0
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <robot_moveResult>))
  "Converts a ROS message object to a list"
  (cl:list 'robot_moveResult
    (cl:cons ':finalpose_x (finalpose_x msg))
    (cl:cons ':finalpose_y (finalpose_y msg))
))
