(cl:defpackage learning_action2-msg
  (:use )
  (:export
   "<FIBONACCIACTION>"
   "FIBONACCIACTION"
   "<FIBONACCIACTIONFEEDBACK>"
   "FIBONACCIACTIONFEEDBACK"
   "<FIBONACCIACTIONGOAL>"
   "FIBONACCIACTIONGOAL"
   "<FIBONACCIACTIONRESULT>"
   "FIBONACCIACTIONRESULT"
   "<FIBONACCIFEEDBACK>"
   "FIBONACCIFEEDBACK"
   "<FIBONACCIGOAL>"
   "FIBONACCIGOAL"
   "<FIBONACCIRESULT>"
   "FIBONACCIRESULT"
  ))

